FROM python:3.6-slim
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app/
RUN pip install -r requirements.txt
COPY . .
RUN echo export PATH="$HOME/.local/bin:$PATH"
EXPOSE 923
ENTRYPOINT ["./entrypoint_dev.sh"]
RUN ["chmod", "+x", "./entrypoint_dev.sh"]
CMD ["start"]
