# Generated by Django 2.0.13 on 2019-07-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('word_type', models.TextField()),
                ('word_length', models.IntegerField(default=0)),
                ('first_sound', models.TextField()),
                ('last_sound', models.TextField()),
                ('simple', models.BooleanField(default=False)),
                ('pos', models.TextField()),
                ('noun', models.BooleanField(default=False)),
                ('very_simple', models.BooleanField(default=False)),
                ('consonants', models.TextField()),
            ],
        ),
    ]
