# Generated by Django 2.0.13 on 2019-07-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='r_chain_easy',
        ),
        migrations.RemoveField(
            model_name='session',
            name='r_chain_hard',
        ),
    ]
