# Generated by Django 2.2.3 on 2019-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.TextField()),
                ('chain_easy', models.IntegerField(default=0)),
                ('chain_hard', models.IntegerField(default=0)),
                ('init_easy', models.IntegerField(default=0)),
                ('init_hard', models.IntegerField(default=0)),
            ],
        ),
    ]
